### ISSUE TITLE
Memory cost when running 

### ISSUE THREAD

**Issue by Fengdan92** [nicolasdugue/DirectedLouvain#2] opened 2017-11-02 19:11 UTC
Hi,

Thank you providing this code for directed louvain algorithm! I'm using it for my research right now, but have encountered a problem with memory management.

I have combined my commands into a bash shell script:
```
#! /bin/bash
work_dir="path of files to be processed "
louvain_dir="path of the executable from directed louvain code"

filename=$1 # name of file that contains the (src dest) information
bactname=$2 # bacteria name. I use this to name the output files

"${louvain_dir}"/convert -i "${work_dir}"/${filename} -o "${work_dir}"/graph_${bactname}.bin -r
"${louvain_dir}"/community "${work_dir}"/graph_${bactname}.bin -l -1 -v > "${work_dir}"/graph_${bactname}.tree 2> "${work_dir}"/M_${bactname}.txt
"${louvain_dir}"/hierarchy "${work_dir}"/graph_${bactname}.tree > "${work_dir}"/hier_${bactname}.txt

level=`grep -i Number "${work_dir}"/hier_${bactname}.txt|cut -c 19` 
# grab the hierarchy level information by searching keyword 'Number'
level=`bc <<EOF
$level - 1
EOF`
echo " > Highest level: $level"

"${louvain_dir}"/hierarchy "${work_dir}"/graph_${bactname}.tree -l $level > "${work_dir}"/partition_${bactname}.txt
# print partition
```
The problem is, when I tried to run the same process many times in parallel (i.e. run one shell script in each of the many parallel processes), I got a warning saying that memory is running out. I think this is because even for one run of ./convert, it takes up ~2GB memory:
![screen shot 2017-11-02 at 2 05 12 pm](https://user-images.githubusercontent.com/22305082/32345187-727033dc-bfd7-11e7-9540-2b58e68d335f.png)

I'm not sure if this is normal, and if this is expected. Could you shed some light onto this issue?

Thank you!

**Comment by nicolasdugue** [comment] 2017-11-03 13:07
Hi,

It may be normal, it depends on the size of your graph. What is the size of your graph file, the edges list ?
We actually load all the edges in memory before converting the graph to a binary compressed spare row graph which is a really efficient structure to deal then with the community detection.
Furthermore, we store edges as pair of long to be able to deal with huge graphs with billions of edges. You may be able to reduce memory usage replacing long by int in our code.
Also, when using renumbering option, one uses more memory, we have extra storage to be able to map former ids with the new ones.

Is this helping ? :)

Regards

**Comment by Fengdan92** [comment] 2017-11-03 17:24
Hi,

Thanks for the response! I'm actually testing my code with a toy model, so the size of my graph is very small (2 nodes, 1 edge). The graph.txt file is 3B in size. 

Maybe it is because the `convert` process naturally takes up a large memory?  I do notice that when I'm running `convert` in parallel, the memory usage of each process is much smaller:
![screen shot 2017-11-03 at 12 19 51 pm](https://user-images.githubusercontent.com/22305082/32387166-9f99d6e6-c091-11e7-9a41-224cb609ebc0.png)
(in this case I get a warning about memory running out again).

Is there anything you can think of that contributes to high memory usage even if the graph file is small?

Thank you!

**Comment by Fengdan92** [comment] 2017-11-05 21:12
Hi,

It looks like the renumeration process is the reason for this memory issue. All of the above were tested on my MacOS. Interestingly, if I run command `./bin/convert -o graph.txt -o graph.bin -r` on Ubuntu, I get the the following core dumped error:
```
Renumerotation begins...
terminate called after throwing an instance of std::bad_alloc
     what(): std::bad_alloc
Aborted (core dumped)
```
But everything runs fine if I do not do renumeration: `/bin/convert -o graph.txt -o graph.bin`.

Could you look into the issue and see if there can be a fix?

Thank you!

**Comment by nicolasdugue** [comment] 2017-11-06 12:25
Hi,
Yes sure, I will take a look at these problems this week: 

- Is your graph weighted ? If it is weighted, the correct line to use renumbering is: 
```
./bin/convert -i graph/graph.txt -o blabla.bin -w -r
```
However, you are right, it seems that there is a problem with the "-r" when dealing with unweighted graphs. I will fix this soon.

- About the memory cost, we designed the algorithm so it is able to deal with huge graphs. So, before renumbering, it is creating a lot of data structures so it can store efficiently the graph. In your case, all these structures are useless. I may propose a "-s" option to tell the algorithm the graph is "small" so it does not run this process.

Regards

**Comment by Fengdan92** [comment] 2017-11-06 17:55
Hi,
Thank you for the reply!

- No, it is not weighted.

- Thanks for the explanation. Yeah, my test graph is very small (just several nodes and edges). Even for my research it will be around 1500 nodes and 3000 edges. 

Best

**Comment by nicolasdugue** [comment] 2017-11-08 13:33
Hi,

I am still working to debug the program but I am not able to figure out what is happening so far. Indeed, I was able to reproduce the bug you noticed on Ubuntu, but when using valgrind to debug, it seems to work.
And actually, it depends if I run the code from the root of the project, or from the bin directory.

However, the program can be used, and it may be using less memory now.
Here are a few recommendations, please tell me if you still are encoutering any problems : 
- I designed a "-n" option that can be used to specify the max id in the file to renumber. 
For example, you can run this at the root of the project
```
./bin/convert -i graph/graph.txt -o gr.bin -r -n 20000
```
- These commands are working fine on ubuntu  : 
```
./bin/convert -i graph/graph.txt -o gr.bin -w test.weights
./bin/convert -i graph/graph.txt -o gr.bin -r -w test.weights
./bin/convert -i graph/graph_uw.txt -o u.bin
```
But this one does not : 
```
./bin/convert -i graph/graph_uw.txt -o u.bin -r
```
However this one does work when runned in the bin directory, and the file renumbered is correct :
```
./convert -i ../graph/graph_uw.txt -o u.bin -r
```

**Comment by Fengdan92** [comment] 2017-11-08 16:20
Hi,

Thank you for looking into this problem. Looks like the -r problem is specific to Ubuntu, as I tested the code on Red Hat 7 and it worked fine. 

Also, could you explain the "-n" option more? If my graph.txt looks like
```
1 2
2 3
3 2
2 5
5 3
```
should I choose n as 4 since there are 4 nodes in total, or should I choose n as 5 as the max id is 5?

**Comment by nicolasdugue** [comment] 2017-11-08 16:32
You should choose 5 in this case.
But actually, I designed the app so that if you choose less or more than 5, it is gonna work. If you choose more than 5, you will use more RAM, and if you choose less than 5, the program will be a bit slower.

Ok, good to know for ubuntu. I never had this problem before, so its cool to know that it seems to be specific to this OS.

Is it using less RAM than before ?

**Comment by Fengdan92** [comment] 2017-11-08 16:46
Yes! Much less. Thanks :)

**Comment by nicolasdugue** [comment] 2017-11-08 16:47
Glad to know !

**Comment by nicolasdugue** [comment] 2017-11-08 16:49
I thus close the issue :)

**Closed as completed** 2017-11-08 16:49 UTC
